### PR TITLE
fix: add a test for solution-alternate.ts and fix its bugs

### LINKED ISSUE #271: 🐛 Bug: projects/arrays/text-processor/src/solution-alternate.ts has some bugs
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/LearningTypeScript/projects/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.
- [X] This is the appropriate issue form for the bug I would like to report.

### Expected

I forked this test file `projects/arrays/text-processor/src/index.test.ts` to a new file named `projects/arrays/text-processor/src/index-alternate.test.ts`
and changes a little in order to test `projects/arrays/text-processor/src/solution-alternate.ts`.

Here is the content of `index-alternate.test.ts`:

```js
import { describe, expect, test } from "@jest/globals";
import { expectType } from "tsd";

import * as index from "./index";
import * as solution_alternate from "./solution-alternate";

// only for quick testing
process.env.TEST_SOLUTIONS = "1"

const { alignTexts } = process.env.TEST_SOLUTIONS ? solution_alternate : index;

describe(alignTexts, () => {
	describe("types", () => {
		test("function type", () => {
			expectType<
				(
					texts: string[],
					options: { align?: "left" | "middle" | "right"; width: number }
				) => string[][]
			>(alignTexts);
		});

		test("return type", () => {
			expectType<string[][]>(alignTexts([], { width: 0 }));
		});
	});

	const cases: [string[], index.AlignmentOptions, string[][]][] = [
		[[""], { width: 0 }, [[""]]],
		[["", ""], { width: 0 }, [[""], [""]]],
		[[""], { width: 2 }, [["  "]]],
		[["abc"], { width: 5 }, [["abc  "]]],
		[["abc def"], { width: 8 }, [["abc def "]]],
		[
			["ab de", "abc def"],
			{ width: 4 },
			[
				["ab  ", "de  "],
				["abc ", "def "],
			],
		],
		[
			["ab de", "abc def", "abcd ef"],
			{ width: 4 },
			[
				["ab  ", "de  "],
				["abc ", "def "],
				["abcd", "ef  "],
			],
		],
		[["ab de", "abc def"], { width: 5 }, [["ab de"], ["abc  ", "def  "]]],
		[["abc def", "abc def"], { width: 8 }, [["abc def "], ["abc def "]]],
		[
			["abc def", "abc def ghi"],
			{ width: 3 },
			[
				["abc", "def"],
				["abc", "def", "ghi"],
			],
		],
		[
			["abc def", "abc def ghi"],
			{ width: 5 },
			[
				["abc  ", "def  "],
				["abc  ", "def  ", "ghi  "],
			],
		],
		[["abc def", "abcdefghi"], { width: 8 }, [["abc def "], ["abcdefghi"]]],
		[[""], { align: "left", width: 0 }, [[""]]],
		[[""], { align: "left", width: 1 }, [[" "]]],
		[[""], { align: "left", width: 2 }, [["  "]]],
		[["abc"], { align: "left", width: 3 }, [["abc"]]],
		[["abc"], { align: "left", width: 4 }, [["abc "]]],
		[["abc"], { align: "left", width: 5 }, [["abc  "]]],
		[["abc def"], { align: "left", width: 7 }, [["abc def"]]],
		[["abc def"], { align: "left", width: 8 }, [["abc def "]]],
		[["abc def"], { align: "left", width: 9 }, [["abc def  "]]],
		[["abc def"], { align: "left", width: 10 }, [["abc def   "]]],
		[["abc def"], { align: "left", width: 11 }, [["abc def    "]]],
		[
			["a", "ab", "abc", "abcd"],
			{ align: "middle", width: 4 },
			[[" a  "], [" ab "], ["abc "], ["abcd"]],
		],
		[[""], { align: "middle", width: 0 }, [[""]]],
		[[""], { align: "middle", width: 1 }, [[" "]]],
		[[""], { align: "middle", width: 2 }, [["  "]]],
		[["abc"], { align: "middle", width: 3 }, [["abc"]]],
		[["abc"], { align: "middle", width: 4 }, [["abc "]]],
		[["abc"], { align: "middle", width: 5 }, [[" abc "]]],
		[["abc def"], { align: "middle", width: 7 }, [["abc def"]]],
		[["abc def"], { align: "middle", width: 8 }, [["abc def "]]],
		[["abc def"], { align: "middle", width: 9 }, [[" abc def "]]],
		[["abc def"], { align: "middle", width: 10 }, [[" abc def  "]]],
		[["abc def"], { align: "middle", width: 11 }, [["  abc def  "]]],
		[
			["abc def", "abc def ghi"],
			{ align: "middle", width: 5 },
			[
				[" abc ", " def "],
				[" abc ", " def ", " ghi "],
			],
		],
		[[""], { align: "right", width: 0 }, [[""]]],
		[[""], { align: "right", width: 1 }, [[" "]]],
		[[""], { align: "right", width: 2 }, [["  "]]],
		[["abc"], { align: "right", width: 3 }, [["abc"]]],
		[["abc"], { align: "right", width: 4 }, [[" abc"]]],
		[["abc"], { align: "right", width: 5 }, [["  abc"]]],
		[["abc def"], { align: "right", width: 7 }, [["abc def"]]],
		[["abc def"], { align: "right", width: 8 }, [[" abc def"]]],
		[["abc def"], { align: "right", width: 9 }, [["  abc def"]]],
		[["abc def"], { align: "right", width: 10 }, [["   abc def"]]],
		[["abc def"], { align: "right", width: 11 }, [["    abc def"]]],
		[
			["abc def", "abc def ghi"],
			{ align: "right", width: 5 },
			[
				["  abc", "  def"],
				["  abc", "  def", "  ghi"],
			],
		],
	];

	test.each(cases)("%j %o", (lines, options, aligned) => {
		expect(alignTexts(lines, options)).toEqual(aligned);
	});
});
```
As usual, I expect all tests will be passed.

### Actual

But I got many tests failed.

Here is the key part of the test output:
```
> test:alertnate
> cross-env TEST_SOLUTIONS=1 jest ./src/index-alternate.test.ts

 FAIL  src/index-alternate.test.ts
  alignTexts
    √ [""] { width: 0 } (2 ms)
    √ ["",""] { width: 0 }
    × [""] { width: 2 } (4 ms)
    × ["abc"] { width: 5 } (1 ms)
    × ["abc def"] { width: 8 } (1 ms)
    × ["ab de","abc def"] { width: 4 } (1 ms)
    × ["ab de","abc def","abcd ef"] { width: 4 } (2 ms)
    × ["ab de","abc def"] { width: 5 }
    × ["abc def","abc def"] { width: 8 } (1 ms)
    √ ["abc def","abc def ghi"] { width: 3 }
    × ["abc def","abc def ghi"] { width: 5 } (1 ms)
    × ["abc def","abcdefghi"] { width: 8 } (1 ms)
    √ [""] { align: 'left', width: 0 }
    × [""] { align: 'left', width: 1 }
    × [""] { align: 'left', width: 2 } (1 ms)
    √ ["abc"] { align: 'left', width: 3 } (1 ms)
    × ["abc"] { align: 'left', width: 4 } (1 ms)
    × ["abc"] { align: 'left', width: 5 } (1 ms)
    √ ["abc def"] { align: 'left', width: 7 }
    × ["abc def"] { align: 'left', width: 8 } (1 ms)
    × ["abc def"] { align: 'left', width: 9 } (1 ms)
    × ["abc def"] { align: 'left', width: 10 }
    × ["abc def"] { align: 'left', width: 11 } (1 ms)
    × ["a","ab","abc","abcd"] { align: 'middle', width: 4 } (1 ms)
    √ [""] { align: 'middle', width: 0 }
    × [""] { align: 'middle', width: 1 } (1 ms)
    × [""] { align: 'middle', width: 2 }
    × ["abc"] { align: 'middle', width: 3 }
    × ["abc"] { align: 'middle', width: 4 } (1 ms)
    √ ["abc"] { align: 'middle', width: 5 }
    × ["abc def"] { align: 'middle', width: 7 }
    × ["abc def"] { align: 'middle', width: 8 } (1 ms)
    √ ["abc def"] { align: 'middle', width: 9 } (1 ms)
    × ["abc def"] { align: 'middle', width: 10 } (1 ms)
    × ["abc def"] { align: 'middle', width: 11 }
    √ ["abc def","abc def ghi"] { align: 'middle', width: 5 } (1 ms)
    √ [""] { align: 'right', width: 0 } (1 ms)
    × [""] { align: 'right', width: 1 }
    × [""] { align: 'right', width: 2 } (1 ms)
    √ ["abc"] { align: 'right', width: 3 }
    × ["abc"] { align: 'right', width: 4 }
    × ["abc"] { align: 'right', width: 5 } (1 ms)
    √ ["abc def"] { align: 'right', width: 7 }
    × ["abc def"] { align: 'right', width: 8 } (1 ms)
    × ["abc def"] { align: 'right', width: 9 }
    × ["abc def"] { align: 'right', width: 10 } (1 ms)
    × ["abc def"] { align: 'right', width: 11 } (1 ms)
    × ["abc def","abc def ghi"] { align: 'right', width: 5 }
    types
      √ function type (1 ms)
      √ return type
```

### Impacted Project

> [projects/arrays/text-processor/src/solution-alternate.ts](https://github.com/LearningTypeScript/projects/blob/main/projects/arrays/text-processor/src/solution-alternate.ts)

### Additional Info

So I read through  this file `solution-alternate.ts` and found some issues.

```typescript
const aligners = {
	left: (line: string, width: number) => line.padEnd(width),
	middle: (line: string, width: number) => {
		const remainingSpaces = width - line.length;

		return remainingSpaces
			? [
				// #3 use string.repeat method is more succinct, The result of Array.from() is weird on some test cases.
				// Array.from({ length: Math.floor(remainingSpaces / 2) }, () => " "),
				" ".repeat(Math.floor(remainingSpaces / 2)),
				line,
				// Array.from({ length: Math.ceil(remainingSpaces / 2) }, () => " ")
				" ".repeat(Math.ceil(remainingSpaces / 2))
			].join("")
			: line;
	},
	right: (line: string, width: number) => line.padStart(width) // #1 should be padStart, not padEnd
};

function alignLines(
	lines: string[],
	{ align = "left", width }: AlignmentOptions
) {
	const aligner = aligners[align];
	// #2 original logic is wrong
	return lines.map((line, index, lines) => {
		return aligner(line, width);
	});
}
```

- `#1` typo: padEnd should be padStart
- `#2` use explicit callback and call aligner function with correct paramters.
- `#3` use string.repeat() helper method because the result of Array.from() is weird on some test cases. See the example below for more details.

## Reproduce Array.from() bug
```js
// Problematic case:
// [["abc def"], { align: "middle", width: 11 }, [["  abc def  "]]],

const remainingSpaces = 4
let s = [
	// #3
	Array.from({ length: Math.floor(remainingSpaces / 2) }, () => " "),
	"abc def",
	Array.from({ length: Math.ceil(remainingSpaces / 2) }, () => " ")
].join("");

console.log(s)
// , abc def ,
// Note the result has two comma `,` marks, not got "  abc def  ".
```

## final

After the fix above, all tests have passed in my local enviroment.

### PR DESCRIPTION
**Pull request by wdpm**
## PR Checklist

- [x] Addresses an existing open issue: fixes #271
- [x] That issue was marked as [accepting prs](https://github.com/LearningTypeScript/projects/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/LearningTypeScript/projects/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

`solution-alternate.ts` has no test before, now it has. And fix some logical errors of `solution-alternate.ts`.

### CODE REVIEW

File: projects/arrays/text-processor/src/solution-alternate.ts [hunk 1]
```diff
@@ -36,18 +36,21 @@ const aligners = {
...
 
 function alignLines(
 	lines: string[],
 	{ align = "left", width }: AlignmentOptions
 ) {
-	return lines.map(aligners[align], width);
+	const aligner = aligners[align];
+	return lines.map((line, index, lines) => {
+		return aligner(line, width);
+	});
```
Comment (JoshuaKGoldberg) [inline projects/arrays/text-processor/src/solution-alternate.ts:55]: I'm just nitpicking, but in the name of simplicity I think we can get this down to one line or so:

```suggestion
	return lines.map((line) => aligners[align](line, width));
```

File: projects/arrays/text-processor/src/solution-alternate.ts [hunk 2]
```diff
@@ -36,18 +36,21 @@ const aligners = {
 
 		return remainingSpaces
 			? [
-					Array.from({ length: Math.floor(remainingSpaces / 2) }, () => " "),
+					" ".repeat(Math.floor(remainingSpaces / 2)),
 					line,
-					Array.from({ length: Math.ceil(remainingSpaces / 2) }, () => " "),
-			  ].join(" ")
+					" ".repeat(Math.ceil(remainingSpaces / 2)),
```
Comment (JoshuaKGoldberg) [inline projects/arrays/text-processor/src/solution-alternate.ts:41]: I like this!

File: projects/arrays/text-processor/src/solution-alternate.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply projects/arrays/text-processor/src/solution-alternate.ts]: Everything is working so I'll push this up now 👍

**Review by JoshuaKGoldberg — APPROVED** [review]
💖 this is wonderful, thanks @wdpm! Adding a specific test for the alternate solution is a nice touch.

File: projects/arrays/text-processor/src/index-alternate.test.ts [hunk 3]
```diff
@@ -0,0 +1,126 @@
+import { describe, expect, test } from "@jest/globals";
+import { expectType } from "tsd";
+
+import * as index from "./index";
+import * as alternate from "./solution-alternate";
+
+const { alignTexts } = process.env.TEST_SOLUTIONS ? alternate : index;
```
Comment (JoshuaKGoldberg) [inline projects/arrays/text-processor/src/index-alternate.test.ts:7]: CI scripts were renaming `solution_alternate` to `index_alternate`, so I just renamed it to `alternate`.
